### ISSUE TITLE
Needed: Creation of contributing.md document 

### ISSUE THREAD

**Issue by motuncoded** [Aneeshaik/gym-app#1]
This repository lacks contributing.md file for contributors  to know how to contribute.

**Comment by Aneeshaik** [comment]
> This repository lacks contributing.md file for contributors to know how to contribute.

Hey @motuncoded! Please go ahead with the contributing.md file. Thank You!

**Comment by danieltayal07** [comment]
> > hey! @motuncoded sir hope you are good, i can contribute in this, please assign me this if possible!
> > Thanks!
> 
> Hey @danieltayal07! As he opened the issue first, I assigned this to him. No worries! please open another issue and I'll definitely assign that to you. I appreciate your interest!

sure and my bad !

**Comment by motuncoded** [comment]
Will work on it

**Comment by motuncoded** [comment]
remote: Permission to Aneeshaik/gym-app.git denied to motuncoded.
fatal: unable to access 'https://github.com/Aneeshaik/gym-app.git/': The requested URL returned error: 403

I am getting this while pushing

**Comment by Aneeshaik** [comment]
> remote: Permission to Aneeshaik/gym-app.git denied to motuncoded.
> fatal: unable to access 'https://github.com/Aneeshaik/gym-app.git/': The requested URL returned error: 403
> 
> I am getting this while pushing
> 

Hey @motuncoded! Please fork the repo and then push the code in the repo. Then, merge and pull.

**Comment by Aneeshaik** [comment]
Hey @motuncoded! I see that you've successfully made PR. Will going to review it soon and Merge it. Thanks for your efforts!

**Comment by motuncoded** [comment]
Ok... Will be waiting for that
