### ISSUE TITLE
[Feature]: Improving Home Page Style and Responsiveness

### ISSUE THREAD

**Issue by Picodes10** [Aneeshaik/gym-app#11]
The home page needs styling, such as a headline, tagline, background effects, and proper layout, to match Batman.

I want to work on this feature @Aneeshaik.

**Comment by Aneeshaik** [comment]
> The home page needs styling, such as a headline, tagline, background effects, and proper layout, to match Batman.
> 
> I want to work on this feature @Aneeshaik.

Hey @Picodes10! Please go ahead. I'm assigning this to you. Thanks for your efforts
