### ISSUE TITLE
Needed: Add License to the Project

### ISSUE THREAD

**Issue by Saiharitha3** [Aneeshaik/gym-app#12]
The project currently lacks a license, which creates uncertainty about usage rights and contributions. Adding a license will ensure transparency and compliance, encouraging more contributors to participate.

By adding a license, users and contributors will have a clear understanding of their rights and obligations. It is also a good practice for open-source projects.

If you find this useful, please assign it to me under Hacktoberfest 2024.

**Comment by Aneeshaik** [comment]
> The project currently lacks a license, which creates uncertainty about usage rights and contributions. Adding a license will ensure transparency and compliance, encouraging more contributors to participate.
> 
> By adding a license, users and contributors will have a clear understanding of their rights and obligations. It is also a good practice for open-source projects.
> 
> If you find this useful, please assign it to me under Hacktoberfest 2024.

Hey @Saiharitha3! Please go ahead. I'm assigning it to you. Thanks for the efforts

**Comment by Saiharitha3** [comment]
Thank you! Do you have any preference for the type of license to be added?

**Comment by Saiharitha3** [comment]
Thank you

**Comment by Saiharitha3** [comment]
please review PR #13

**Comment by Aneeshaik** [comment]
Completed by @Saiharitha3
