### ISSUE TITLE
Mobile Devices Responsive Design Issues(hacktoberfest)

### ISSUE THREAD

**Issue by MARKASCHARAN** [Aneeshaik/gym-app#17]
Description:
The website does not display properly on mobile devices. Certain elements, such as the navbar, images,text content, are not responsive and appear distorted. This issue affects the overall user experience on smaller screens.

Steps to Reproduce:

Open the website on a mobile device or use browser developer tools to simulate a mobile screen.
Observe that the layout is distorted.
Expected Behavior:
The website should be fully responsive and adjust its layout to fit smaller screen sizes without breaking or distorting any elements.

Screenshots:
<img width="1470" alt="Screenshot 2024-10-22 at 11 56 28 AM" src="https://github.com/user-attachments/assets/f9c88199-fd83-459a-a0ae-9e2b16f510fa">

Assign me, I can make it mobile responsive.

**Comment by Aneeshaik** [comment]
> Description: The website does not display properly on mobile devices. Certain elements, such as the navbar, images,text content, are not responsive and appear distorted. This issue affects the overall user experience on smaller screens.
> 
> Steps to Reproduce:
> 
> Open the website on a mobile device or use browser developer tools to simulate a mobile screen. Observe that the layout is distorted. Expected Behavior: The website should be fully responsive and adjust its layout to fit smaller screen sizes without breaking or distorting any elements.
> 
> Screenshots: <img alt="Screenshot 2024-10-22 at 11 56 28 AM" width="1470" src="https://private-user-images.githubusercontent.com/133427225/378708832-f9c88199-fd83-459a-a0ae-9e2b16f510fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjQ2MTksIm5iZiI6MTcyOTY2NDMxOSwicGF0aCI6Ii8xMzM0MjcyMjUvMzc4NzA4ODMyLWY5Yzg4MTk5LWZkODMtNDU5YS1hMGFlLTllMmIxNmY1MTBmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwNjE4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDQ0MzJiMzM4ZjkwYjAzMDc0YTdmMGFmYTFlNDRjZjE2YzU1MDAxZGM0ODI4MjljMzRmMmY2MTMwN2VhYmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zXh_sTqJ8Dn7H6g_KlKWnhEWTRBCbYRZi8uVKEzrDCM">
> 
> Assign me, I can make it mobile responsive.

Hey @MARKASCHARAN! I thought it to make it responsive once the website is fully made with the features I want. No worries! Once the website is made, be there for me. I will definitely work with you in near future
