### ISSUE TITLE
Enhance navbar and update contents of home page for better UI 

### ISSUE THREAD

**Issue by navyaajainnn** [Aneeshaik/gym-app#20]
Description:
The current navbar of website looks very boring and simple. In order to make website more interactive we have to give it a new design. The home page looks kinda distorted too, soo changing it into something beautiful would attract more users 

![Screenshot 2024-10-22 151645](https://github.com/user-attachments/assets/d4aac3d8-af2a-4d05-97ef-a60d6f8a0fc3)

Expected Outcome:
Update the navbar to something interactive and more accessible 
Ensure the home page contains all relevant details that the user needs along with relevant pictures 

To Do:
Design new navbar 
Change contents of home page 

Assign me, do let me know if you have any requirements for the design of navbar and home page specifically. I would love to work on it

**Comment by navyaajainnn** [comment]
hey @Aneeshaik, please assign this issue to me 
Please add tags of hacktober and design as well! Thanks

**Comment by Aneeshaik** [comment]
Hey @navyaajainnn! Please go ahead with this and please upload the video of your changes what you did while doing PR. Thank you for your efforts
