### ISSUE TITLE
I can Dockerised the all the dependencies and techology in the docker fille 

### ISSUE THREAD

**Issue by shashishsoni** [Aneeshaik/gym-app#21]
hello there,

I can dockerize all the dependencies and technologies in the Dockerfile and build your project using Docker.

[✅ ] Hacktoberfest
[✅ ] Hacktoberfest-accepted

can you assign me this work or this issue to me

**Comment by Aneeshaik** [comment]
Hey @shashishsoni! As I don't have enough knowledge of Docker, I don't think it will be the good move no go with
