### ISSUE TITLE
Add Scroll Effects, Dark/Light Mode, Card Layouts, and Hero Section Video

### ISSUE THREAD

**Issue by Che140401** [Aneeshaik/gym-app#22]
I'd like to propose the following enhancements to improve the gym app:

1. Scroll Effects: Add smooth scroll animations and subtle transitions for a more engaging user experience.
2. Dark/Light Mode: Add a toggle to switch between dark and light themes, ensuring accessibility and visual appeal.
3. Card Layouts: Use card layouts for sections like workout plans and trainer profiles for better content organization.
4. Hero Section Video: Replace the static hero section with an auto-playing video showcasing gym activities or promotions.

video link - https://www.loom.com/share/73bfe87db913428d907e849237dc29b1?sid=318d7af1-b27d-4cc6-ae8e-4490f09c7ec5

ScreenShot - 
![FireShot Capture 003 - Get the Best Fitness Workouts, Gyms and Sports in India - cult fit_ - www cult fit](https://github.com/user-attachments/assets/ed816ac9-6e00-4393-86b0-36ca9e632d4a)

**Comment by Aneeshaik** [comment]
Hey @Che140401! Please go ahead and we don't have a trainers section in that. Our goal is to provide workouts and diet to users from that website only. Please make sure to upload a video of your changes while doing PR.

**Comment by Che140401** [comment]
We've added a hero section video and a card layout for the fitness website!
link:-https://www.loom.com/share/ca84aa0f7a3b481786c5f3ac7f046d7b?sid=8189ac02-a7ac-4c52-b886-d962753b07f1

**Comment by Aneeshaik** [comment]
Thank you @Che140401
