### ISSUE TITLE
Fix: Restructure of the website HTML

### ISSUE THREAD

**Issue by motuncoded** [Aneeshaik/gym-app#3]
The website structure need to be restructured

**Comment by Aneeshaik** [comment]
Hello @motuncoded! Do you any sample or idea how to restructure?

**Comment by motuncoded** [comment]
No. The essence of this is to have a proper and accessible HTML structure.

**Comment by motuncoded** [comment]
kindly assign this to me

**Comment by Aneeshaik** [comment]
Okay @motuncoded! I'm assigning this to you. Please structure it with your creative and mind blowing ideas. Will review it and if it is amazing then definitely I'll Merge this too. Thanks for your amazing efforts

**Comment by motuncoded** [comment]
Helo, I would like to uninstall parcel. it is basically for small projects and it is causing issues after the installation of react router dom when trying to restructure the pages

**Comment by motuncoded** [comment]
Can I go ahead with this installation?
