### ISSUE TITLE
UI is not proper, animations not there, Navbar not properly designed

### ISSUE THREAD

**Issue by Saachi30** [Aneeshaik/gym-app#30]
I have made some changes in the ui of the website and added animations

## Before
![image](https://github.com/user-attachments/assets/94a89307-39ba-4707-abb1-75d3eb4536ed)

## After
![image](https://github.com/user-attachments/assets/c0d4e2f7-a073-4f8a-9cbb-74a34a84af4f)

Please assign this issue to me so that I can raise the PR today itself

**Comment by Aneeshaik** [comment]
Hey @Saachi30! It's really amazing. Thanks for your efforts. Can you please enhance the nav section too?

**Comment by Aneeshaik** [comment]
hey @Saachi30! Please look into the issue #24 and make it like that with the cleanness how you maintained in the above enhancement. It's really clean and nice. If you any further creative ideas please feel free to share those here.
