### ISSUE TITLE
Needed: Add Readme File

### ISSUE THREAD

**Issue by Devashish-Mishra-2003** [Aneeshaik/gym-app#4]
By adding readme file contributor will come to know how to contribute in your project and it is also a good practice. if you find this helpul pls assign it to me under hacktoberfest 2024.

Thanking You!!

**Comment by Aneeshaik** [comment]
Sure @Devashish-Mishra-2003! Go ahead with this.

**Comment by Saiharitha3** [comment]
Hi @Aneeshaik i am ready to provide my help here

**Comment by Aneeshaik** [comment]
> Hi @Aneeshaik i am ready to provide my help here

Hey @Saiharitha3! As @Devashish-Mishra-2003 opened the issue I've assigned this to him. But, you can also create Readme file. I'll go through both readme files and merge which is nearly related to the project features. Thank You!

**Comment by Saiharitha3** [comment]
Thank You!

**Comment by Saiharitha3** [comment]
please review PR #15

**Comment by Aneeshaik** [comment]
> please review PR #15

Merged. Can you add the contributors in Readme file and thank them? I hope you got my point

**Comment by Saiharitha3** [comment]
yeah sure i can add that

**Comment by Aneeshaik** [comment]
> yeah sure i can add that

Hey @Saiharitha3! Are you working on it?

**Comment by Saiharitha3** [comment]
please review PR #36
