### ISSUE TITLE
Improvement of Nav Bar and Hero Section

### ISSUE THREAD

**Issue by KARANSINGH34951** [Aneeshaik/gym-app#5]
Currently its lacks many basic functionalities.
![Screenshot 2024-10-21 185736](https://github.com/user-attachments/assets/7322826a-b713-418d-8585-fbddb5c13e58)

**Comment by Ncode-93** [comment]
Hey @Aneeshaik I can work on this issue.

**Comment by Aneeshaik** [comment]
> Currently its lacks many basic functionalities.
> ![Screenshot 2024-10-21 185736](https://github.com/user-attachments/assets/7322826a-b713-418d-8585-fbddb5c13e58)
> 

Please go ahead with your creative ideas for the navbar. I'm assigning this to you

**Comment by Aneeshaik** [comment]
> Hey @Aneeshaik I can work on this issue.

Hey @Ncode-93! You can work on this. But, as @KARANSINGH34951 opened this issue, more preference will be given to him. But if your work is more creative then I'll merge your PR. If you want to work on a new issue, you can open an another issue.

**Comment by Aneeshaik** [comment]
> hey i can wokr this issue
> 
Hey @JhoanAlvear! You can work on this. But, as @KARANSINGH34951 opened this issue, more preference will be given to him. But if your work is more creative then I'll merge your PR. If you want to work on a new issue, you can open an another issue.
